resources:
  - name: simple-repo
    type: git
    source:
      uri: https://github.com/msherman/simple.git
      branch: master

jobs:

  - name: source-images
    plan:
      - get: simple-repo
        trigger: true
      - task: get-images
        file: simple-repo/config/jobs/no-op.yml

  - name: deploy-dev
    plan:
      - get: simple-repo
        trigger: true
        passed: [source-images]
      - task: deploy
        file: simple-repo/config/jobs/no-op.yml

  - name: deploy-test
    plan:
      - get: simple-repo
        trigger: true
        passed: [deploy-dev]
      - task: deploy
        file: simple-repo/config/jobs/no-op.yml

  - name: deploy-prod
    plan:
      - get: simple-repo
        passed: [deploy-test]
      - task: deploy
        file: simple-repo/config/jobs/no-op.yml