resources:
  - name: simple-repo
    type: git
    source:
      uri: https://github.com/msherman/simple.git
      branch: master

jobs:
  - name: frontend linter
    plan:
      - get: simple-repo
      - task: run linter
        file: simple-repo/config/jobs/run-frontend-tests.yml

  - name: frontend tests
    plan:
      - get: simple-repo
        passed: [frontend linter]
      - task: run-tests
        file: simple-repo/config/jobs/run-frontend-tests.yml